FROM joseluisq/static-web-server:2

ARG BUILD_DIR
ARG BASE_HREF=/

ENV SERVER_FALLBACK_PAGE=/public${BASE_HREF}index.html

COPY ${BUILD_DIR} /public${BASE_HREF}
COPY --chmod=644 static-web-server.toml /sws.toml

EXPOSE 8080

ENTRYPOINT ["/static-web-server"]
CMD ["-p", "8080", "-d", "/public", "-w", "/sws.toml"]
